server:
  port: ${PORT:8091}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    domain: 'DEBUG'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/